apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usm-ingress
spec:
  rules:
  - host: grafana.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: my-grafana
            port:
              number: 80
  - host: zipkin.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: zipkin
            port:
              number: 9411
  - host: notificatiion.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: usm-notification-service
            port:
              number: 80
  - host: prometheus.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prometheus-service
            port:
              number: 80
  # - host: eureka.rancher.localhost
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: /
  #       backend:
  #         service:
  #           name: eureka-np
  #           port:
  #             number: 8110
  # - host: keycloak.rancher.localhost
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: /
  #       backend:
  #         service:
  #           name: usm-keycloak-service
  #           port:
  #             number: 80