apiVersion: apps/v1
kind: Deployment
metadata:
  name: usm-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usm-discovery
  template:
    metadata:
      labels:
        app: usm-discovery
    spec:
      containers:
        - name: usm-discovery-ctr
          image: 5927055/usm-discovery:efaf9b1
          env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://temp-service:4317
          - name: OTEL_METRICS_EXPORTER
            value: none 
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #   value: http://temp-service:4318
          # - name: OTEL_METRICS_EXPORTER
          #   value: none 
          # - name: OTEL_TRACES_EXPORTER
          #   value: zipkin   
          # - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
          #   value: http://temp-service:9411
          imagePullPolicy: Always
          ports:
            - containerPort: 8110
---
apiVersion: v1
kind: Service
metadata:
  name: usm-discovery-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8110
    nodePort: 30000
  selector:
    app: usm-discovery

    