kind: Service
apiVersion: v1
metadata:
  name: usm-db
spec:
  clusterIP: None
  ports:
  - port: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
  name: usm-db
subsets:
  - addresses:
        - ip: 10.4.152.152
    ports:
      - port: 5432
        name: usm-db